### ISSUE TITLE
[+1] Standard user management

### ISSUE THREAD

**Issue by minthe** [minthe/ft_transcendence#29]
User Management

- [x]  Users can subscribe to the website in a secure way
- [x]  Registered users can log in in a secure way
- [x] #97
- [x]  Users can update their information
- [x] #54
- [x] #105
- [x] #107
- [x] #106

https://www.notion.so/Transcendence-Checklist-01f2a78c3ea14a96af1fe26b1780d396?pvs=4#81581d555ebf4495a0b8ce2d57afe90e

**Comment by cryptoclown132** [comment]
user stats is done #29
