### ISSUE TITLE
repeated click on a chat in the chat list will disconnect the websocket connection

### ISSUE THREAD

**Issue by minthe** [minthe/ft_transcendence#41]
- if i click on a private chat it opens it. if i click on the same chat in the list the connection drops

**Comment by mariekart42** [comment]
i think it happens in chat.js in the if-else statement line 283 and 317.
@cryptoclown132 has probably better understanding of it but it looks like if `state.chatOpen` then 
`console.log('goes back to default and closes');
    hideDiv('messageSide');`

**Comment by minthe** [comment]
https://github.com/minthe/ft_transcendence/blob/e59f46c1e71cdf2329ea232ccb4cefba405fdf56/ms_frontend/root/src/js/chat.js#L283-L284

https://github.com/minthe/ft_transcendence/blob/e59f46c1e71cdf2329ea232ccb4cefba405fdf56/ms_frontend/root/src/js/chat.js#L317-L324

**Comment by cryptoclown132** [comment]
fixed it i just forgot to remove window.history.back();
