### ISSUE TITLE
logout button doesnt changes isOffline state to true anymore 

### ISSUE THREAD

**Issue by mariekart42** [minthe/ft_transcendence#53]
happens cause in [ms_game_chat/backend/backend_app/consumer/websocket.py](https://github.com/minthe/ft_transcendence/blob/main/ms_frontend/root/src/js/websocket.js) line 174 the line with closing the websocket is commented. I guess has some debugging purposes.

Don't need to fix now, just wrote an issue to keep in mind to include `websocket_obj.websocket.close();` later again

**Comment by minthe** [comment]
@mariekart42 is it fixed now?
